DotNetToDoApp_CRUD/ToDo/Models/Item.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ToDo.Models
{
    public class Item 
    {

        [Key]
        public int ID { get; set; }
        public string Name { get; set; }


        [ForeignKey("Category")]
        public int catID { get; set; }
        public virtual Category Category { get; set; }


        public bool Completed { get; set; }
    }
}

DotNetToDoApp_CRUD/ToDo/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ToDo.Models;

namespace ToDo.Controllers
{
    public class ItemsController : Controller
    {
        private tododB db = new tododB();

        public ActionResult Create(int? id)
        {
            ViewBag.catID = id;
            return View();
        }

      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create1([Bind(Include = "ID,Name,catID,Completed")] Item item, string catID)
        {
            if (ModelState.IsValid)
            {
                item.catID = Convert.ToInt32( catID);
                db.Items.Add(item);
                db.SaveChanges();
                TempData["Message"] = "Success";
                return RedirectToAction("Index","List");
            }

            ViewBag.catID = new SelectList(db.Categories, "catID", "Name", item.catID);
            return View(item);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            ViewBag.catID = new SelectList(db.Categories, "catID", "Name", item.catID);
            return View(item);
        }
 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,catID,Completed")] Item item)
        {
            if (ModelState.IsValid)
            {
                TempData["Message"] = "The Item was successfully changed to " + "--" + "" + item.Name + "" + "--" + "!!";
                db.Entry(item).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index","List");
            }
            ViewBag.catID = new SelectList(db.Categories, "catID", "Name", item.catID);
            return View(item);
        }

    
        public ActionResult Delete(int id)
        {
            Item item = db.Items.Find(id);
            db.Items.Remove(item);
            db.SaveChanges();
            TempData["Message"] = "The Item" + "" + "--" + "" + item.Name + "" + "--" +  "was successfully deleted";
            return RedirectToAction("Index","List");
        }

        
        public ActionResult DeleteChecked()
        {
            List<Item> checkedItems = db.Items.Where(selc => selc.Completed == true).ToList();
            foreach ( var item in checkedItems)
            {
                db.Items.Remove(item);
                db.SaveChanges();              
            }
            TempData["Message"] = "The Completed Items have been Removed";
            return RedirectToAction("Index", "List");
        }

        public ActionResult Togglechecked(int? id)
        {
            var Toggleitem = db.Items.Find(id);
            if (Toggleitem.Completed == false)
            {
                Toggleitem.Completed = true;
            }
            else
            {
                Toggleitem.Completed = false;
            }
            db.SaveChanges();
            return RedirectToAction("Index", "List");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DotNetToDoApp_CRUD/ToDo/Views/Items/Create.cshtml
@model ToDo.Models.Item

@{
    ViewBag.Title = "Create";
}

<h2 style="color:white">Add Item to List</h2>

@using (Html.BeginForm("Create1", "Items", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2", @style="color:white" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @required = true } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <input id="catID" name="catID" style="display:none" value="@ViewBag.catID" />
        </div>

        <div style="display:none" class="form-group">
            @Html.LabelFor(model => model.Completed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Completed)
                    @Html.ValidationMessageFor(model => model.Completed, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Back" class="btn btn-danger" style="margin-left:-50px" onclick="window.history.go(-1)" />
    </div>
</div>

DotNetToDoApp_CRUD/ToDo/Views/Items/Edit.cshtml
@model ToDo.Models.Item

@{
    ViewBag.Title = "Edit";
}

<h2 style="color:white">Modify</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2", @style="color:white" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @required = true } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div  style="display:none" class="form-group">
            @Html.LabelFor(model => model.catID, "catID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("catID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.catID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div style="display:none"  class="form-group">
            @Html.LabelFor(model => model.Completed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.HiddenFor(model => model.Completed)
                    @Html.ValidationMessageFor(model => model.Completed, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Back" class="btn btn-danger" style="margin-left:-50px" onclick="window.history.go(-1)" />
    </div>
</div>